---
title: "Actividad Grupal"
author: "Marko Rodríguez, Braulio Yucra, Emanuel Rodríguez"
date: "24/11/2021"
output: github_document
---


```{r}
#1 ¿Qué cantidad de dinero sobra al repartir 10000$ entre 3 
10000%%3
```
```{r}
#2 ¿Es el número 4560 divisible por 3
0 == (4560%%3)
```
```{r}
#3 Construya un vector con los números enteros del 2 al 87. ¿cuales de esos números son divisibles por 7?
n_enteros <- c(2:87)
divisibles_7 <- c(0 == n_enteros%%7)
which( divisibles_7 == TRUE)
divisibles_7[c(6, 13, 20, 27, 34, 41, 48, 55, 62, 69, 76, 83)]
```
```{r}
#4 Construya dos vectores, el primero con los números enteros desde el 7 hasta 3, el segundo vector con los primeros cinco números positivos divisibles por 5.
#4.1 Sea A la condición de ser par en el primer vector
vector_1 <- c(7:3)
which( vector_1%%2 == 0 )
A <- vector_1[c(2, 4)]
A
```

```{r}
#4.2 Sea B la condición de ser mayor que 10 en el segundo vector.
vector_2 <- c( seq ( 5, 25, 5 ))
which( vector_2 > 10 )
B <- vector_2[c(3, 4, 5)]
B
```
```{r}
#4.3 ¿En cual de las 5 posiciones se cumple A y B simultaneamente?
for (i in 1:5) {
  for (j in 1:5){
    if(i==j){
      if(vector_1[i] == vector_2[j]){
      print(i)
    }
}
}
}
print("no hay datos")
```


```{r}
#5
v <- c(1:100)
sum(v)
```
```{r}
#6
v <- c(1,-4,5,9,-4)
which.min(v)
```
```{r}
#7
factorial(8)
```
```{r}
#8
y <- c(3:7)
sum(exp(y))
```
```{r}
#9
x<-c(log10(sqrt(1)),log10(sqrt(2)),log10(sqrt(3)),log10(sqrt(4)),
     log10(sqrt(5)),log10(sqrt(6)),log10(sqrt(7)),log10(sqrt(8)),
     log10(sqrt(9)),log10(sqrt(10)))
prod(x, na.rm=TRUE)
```
```{r}
#10 
Areacorona <- function(x,y){
  ((x)^2)/2*(y-sin(y))
}
Areacorona(4,pi/4)
```
```{r}
#11
Y <- c(1:30)
sort(Y)
sort(Y, decreasing = T)
rev(Y)
```
```{r}
#12
m <- c(10:100)
m^3+(4*m^2)
sum(m^3+(4*m^2))
```
```{r}
#13
n <- c(1:25)
((2^n)/n)+((3^n)/n^2)
sum(((2^n)/n)+((3^n)/n^2))
```
```{r}
#14
dataset <- read.delim("https://raw.githubusercontent.com/fhernanb/datos/master/Paises.txt")
length(dataset)
dataset$Pais[which.max(dataset$poblacion)]
```
```{r}
#15
C <- mtcars
row.names(mtcars)
row.names(mtcars)[which(mtcars$mpg <18)]
row.names(mtcars)[which(mtcars$cyl==4)]
row.names(mtcars)[which(mtcars$wt > 2.5 & mtcars$am == 1)]
```
```{r}
#16
x <- 0:365
y <- 2*3.14*(x-81)/365

Funcion01 <- function(y) {
  x <- 9.87 * 2 * sin(y)*cos(y)-7.53 * cos(y) -1.5 * sin(y)
  return(x)
}
Funcion01(y)
x <-seq(as.Date("2021-01-01"), as.Date("2022-01-01"), "day")

plot(x, Funcion01(y), ylab = "Minutos", xlab = "Meses", col="red", type = "l", lwd = 3, lty = 2)
mtext("Mathematical Astronomy Morsels, Jean Meeus. 1997", side = 3, adj = 0)
title("Ecuación del tiempo",
      adj = 0.000001,
      line = 1.5)
```

